library(tidyverse)
data = read_csv("expression.csv")
groups = group_by(data, Markers)
means = summarise(groups, d0 = mean(D0), d2 = mean(D2), d4 = mean(D4), d6 = mean(D6))
sd = summarise(groups, d0 = sd(D0), d2 = sd(D2), d4 = sd(D4), d6 = sd(D6))
t = t(means)
s = as.data.frame(t[2:5,])
s = rename(s, Cebpa = V1, Fabp4 = V2, Perilipin = V3, Pparg1 = V4, pPparg2 = V5, Setd2 = V6)
r = gather(s, marker, value)
d = c("d0","d2","d4","d6")
d = c(d,d,d,d,d,d)
r = cbind(r,d)
ggplot(r) + geom_bar(aes(d, value), stat = "identity") + facet_wrap(~marker, scales = "free") + theme_bw()
